# Publish on new tag Workflow

name: Publish on new tag

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Display tag
        run: echo "Tag is $TAG"