# Publish on new tag Workflow

name: Publish on new tag

on:
  push:
    tags:
      - '*'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Get Tag
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Display tag
        run: echo "Tag is $TAG"
    # Build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon

    # Publish
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          
          github-tag: $TAG
          github-generate-changelog: true

          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            versions/1.8.9-forge/build/libs/!(*-@(dev|sources|javadoc)).jar
            versions/1.8.9-forge/build/libs/*-@(dev|sources|javadoc).jar

          name: Not Enough Zombies v$TAG
          version: $TAG
          version-type: release

          loaders: forge
          game-versions: 1.8.9
          java: Java 1.8


          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail